# Generated by Django 5.0 on 2024-01-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='taskmodel',
        ),
    ]
