# Generated by Django 5.0 on 2024-01-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_taskcategory_taskmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='Name',
            new_name='name',
        ),
    ]
